name: Deploy com Docker Compose

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: 
      - self-hosted      

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v2
      continue-on-error: false

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2      

    - name: Implantar com Docker Compose
      run: |
        docker compose build
        docker compose up -d  